name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project
        run: |
          ZIP=$(find . -maxdepth 1 -type f -name "*.zip" | head -n 1)
          mkdir project
          unzip -q "$ZIP" -d project
          SETTINGS=$(find project -name "settings.gradle.kts" -type f | head -n 1)
          PROJECT_DIR=$(dirname "$SETTINGS")
          echo "PROJECT_DIR=$PROJECT_DIR" >> "$GITHUB_ENV"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Install SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses || true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          gradle assembleDebug --no-daemon
          -Pandroid.useAndroidX=true \
          -Pandroid.enableJetifier=true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DompetKu-APK
          path: "**/build/outputs/apk/debug/*.apk"
